from datetime import datetime

DEALS_UPDATED_DISCORD_MESSAGE = f'<@&948814795786821643> Update'
DEALS_IMAGE_EMBED_HEADER_MESSAGE = 'New Deal!'
DISCORD_WEBHOOK_BOT_NAME = 'FLCD Bot'
DISCORD_WEBHOOK_AVATAR_URL = 'https://i.imgur.com/dw0uEP8.png'
TWITTER_STATUS_MESSAGE = ''